### ISSUE TITLE
Matrix creation error

### ISSUE THREAD

**Issue by h80r** [thaisclxt/Contrast-Stretching#1]
https://github.com/thaisclxt/Contrast-Stretching/blob/aefc6197e61d45f6066e701a5ad4eecde6ad6ba7/alargamento.py#L7

Nessa linha, ele tá copiando a referência e não o valor, por isso tá dando erro.

**Comment by thaisclxt** [comment]
😱😱😱😱

**Comment by h80r** [comment]
Tem coisas que você copia por valor, como variáveis de tipo simples, `float`, `int`, `bool`, e coisas que são copiadas por referência, como uma `list`.
Copiar por referência significa o seguinte:

```py
lista_1 = [1, 2, 3]
lista_2 = lista_1
lista_2[2] = 7
print(lista_1)
# [1, 2, 7]
```

Isso ocorre porque a cópia por referência não passa pra nova variável o valor que a primeira tá armazenando, e sim o endereço de memória.

**Comment by thaisclxt** [comment]
aaaahhh entendi, vlwww

**Comment by h80r** [comment]
quando corrigir o erro feche a issue ;)

**Comment by thaisclxt** [comment]
sim senhor

**Comment by thaisclxt** [comment]
_Vou de womensplaining aqui, só para eu lembrar do erro e de como corrigi._

- Naquela linha eu estava copiando a referência das listas, já que variáveis do tipo `list` são copiadas por referência:
`list = [[0] * 5] * 4) ` Desta forma, teremos 4 listas contendo os mesmos 5 valores da 1ª lista, ou seja, se posteriormente eu definir `list[2][2] = 8`, `list[0][2]`, `list[1][2]` e `list[2][3]` também terão valor 8.

- O problema pode ser corrigido da seguinte forma:
```
from copy import deedcopy

list = [0] * 5
matrix = []

for _ in range(4):
   matrix.append(deepcopy(list))
```

Ou ainda:

```
matrix = []

for _ in range(4):
   matrix.append(deepcopy([0] * 5)

```

Assim, eu estou copiando o valor, já que [0] é uma variável do tipo `int`.

- Corrigi usando numpy, já que `np.zeros` reserva um lugar na memória para cada valor:

```
import numpy as np

list = np.zeros((4, 5), dtype=int)
```
